### ISSUE TITLE
Step by step guide link is down

### ISSUE THREAD

**Issue by binajmen** [patatoid/boruta_example#1]
Hi @patatoid,

New to Elixir, I would like to use your library to implement an OAuth2 server around my REST API. The link for the step by step guide that describe how to setup a server using Boruta is not working anymore (pointing to a dead link in GitLab).

Could you please reupload this guide ?

Thank you!

**Comment by patatoid** [comment]
Hi,

I just updated the GitLab links, the guide is available in hexdoc - https://hexdocs.pm/boruta/provider_integration.html

https://github.com/patatoid/boruta_example/commit/b7b43f48c621e64d6faf63556c5056827200b06c

If you need any further support, do not hesitate to reach out!
